[project]
name = "siiabackend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django==6.0.2",
    "djangorestframework==3.16.1",
    "django-cors-headers==4.9.0",
    "django-environ==0.12.0",
    "django-filter==25.2",
    "djangorestframework-simplejwt==5.5.1",
    "pytest==9.0.2",
    "pytest-django==4.11.1",
    "mysqlclient==2.2.7",
    "pytest-watcher==0.6.3",
    "django-seeding==1.3.6",
    "pandas==3.0.0",
    "redis==7.1.1"
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F402"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "siia_backend.settings"
python_files = ["test_*.py", "*_test.py", "testing/python/*.py"]
addopts = "--reuse-db"
