# Generated by Django 6.0.2 on 2026-02-10 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoProducto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Catalogo Producto",
                "verbose_name_plural": "Catalogo Productos",
                "db_table": "cvu_catalogo_productos",
            },
        ),
        migrations.CreateModel(
            name="ProductoInvestigador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_producto",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("eje", models.CharField(blank=True, max_length=64, null=True)),
                ("titulo", models.CharField(max_length=512)),
                ("contenido", models.JSONField(blank=True, null=True)),
                ("is_from_file", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "investigador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cvu.catalogoproducto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto Investigador",
                "verbose_name_plural": "Productos Investigadores",
                "db_table": "cvu_productos_investigadores",
            },
        ),
    ]
