# Generated by Django 6.0.2 on 2026-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvu", "0002_catalogoproducto_productoinvestigador"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogoproducto",
            name="label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
