# Generated by Django 6.0.2 on 2026-02-18 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvu", "0003_catalogoproducto_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cvu", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "nivel_academico",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("titulo", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "fotografia_nombre",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "fotografia_content_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("fotografia_uri", models.TextField(blank=True, null=True)),
                ("semblanza", models.TextField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, max_length=512, null=True)),
                ("orcid", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "correo_alternativo",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("curp", models.CharField(blank=True, max_length=18, null=True)),
                ("rfc", models.CharField(blank=True, max_length=13, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("intereses", models.JSONField(blank=True, default=list, null=True)),
                ("habilidades", models.JSONField(blank=True, default=list, null=True)),
                ("sexo", models.JSONField(blank=True, null=True)),
                ("pais_nacimiento", models.JSONField(blank=True, null=True)),
                ("entidad_federativa", models.JSONField(blank=True, null=True)),
                ("estado_civil", models.JSONField(blank=True, null=True)),
                ("nacionalidad", models.JSONField(blank=True, null=True)),
                ("area_conocimiento", models.JSONField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Usuario",
                "verbose_name_plural": "Perfiles Usuarios",
                "db_table": "cvu_perfil_usuarios",
            },
        ),
    ]
