# Generated by Django 6.0.2 on 2026-02-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cvu", "0004_perfilusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="primer_apellido",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="segundo_apellido",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
